options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/be-sembako", "."]
    dir: 'Backend'

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/be-sembako"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "be-sembako",
        "--image",
        "gcr.io/$PROJECT_ID/be-sembako",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--set-env-vars",
        "JWT_SECRET=${_JWT_SECRET},DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},DB_DIALECT=mysql,PORT=5000"
      ]

substitutions:
  _JWT_SECRET: ''        # isi otomatis dari secret manager
  _DB_HOST: ''           # bisa diisi default atau lewat secret manager juga
  _DB_NAME: 'db_sembako' # bisa default juga
  _DB_USER: 'root'       # bisa default juga
  _DB_PASSWORD: ''       # isi otomatis dari secret manager

availableSecrets:
  secretManager:
    - versionName: projects/PROJECT_ID/secrets/db_password/versions/latest
      env: _DB_PASSWORD
    - versionName: projects/PROJECT_ID/secrets/jwt_secret/versions/latest
      env: _JWT_SECRET
