steps:
  - name: node:18
    dir: Backend
    entrypoint: npm
    args: ['install']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE', '.']
    dir: Backend

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    # Ambil secrets dari Secret Manager dan deploy
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_NAME',
        '--image',
        '$_IMAGE',
        '--region',
        '$_REGION',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--set-env-vars',
        'DB_NAME=db_sembako,DB_USER=root,DB_PASSWORD=${_DB_PASSWORD},DB_HOST=YOUR_SQL_HOST,DB_DIALECT=mysql,JWT_SECRET=${_JWT_SECRET}'
      ]

substitutions:
  _DB_PASSWORD: ''  # nanti ini diisi otomatis saat build dengan secret
  _JWT_SECRET: ''
  
availableSecrets:
  secretManager:
    - versionName: projects/PROJECT_ID/secrets/db_password/versions/latest
      env: _DB_PASSWORD
    - versionName: projects/PROJECT_ID/secrets/jwt_secret/versions/latest
      env: _JWT_SECRET

images:
  - $_IMAGE
